version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.7.5
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Write to workspace
          command: echo foobar > workspace/${CIRCLE_NODE_INDEX}/foobar
      - deploy:
          name: Collect Results
          command: |
            ls -R workspace
workflows:
  main:
    jobs:
      - build-and-test
